[phases.setup]
nixPkgs = ['ffmpeg']

[phases.build]
cmds = [
  'pip install -r requirements.txt',
  'mkdir -p backend/staticfiles',
  'cd backend && python manage.py collectstatic --noinput'
]

[start]
# We use bash to run multiple commands: migrate then start gunicorn
cmd = 'cd backend && python manage.py migrate --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 3'
